name: Python Tests

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running tests'
        required: false
        default: 'Manual test run'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run tests with pytest
      run: |
        pytest --cov=src tests/
